### ISSUE TITLE
When will we get executable?

### ISSUE THREAD

**Issue by tusharhero** [biologyscience/overtone#2]

**Comment by biologyscience** [comment]
Of course after the app is finished but I have no idea when it's gonna happen.
###### Hopefully coming March or smth

**Comment by tusharhero** [comment]
Okay then.

**Comment by tusharhero** [comment]
Coming March is already over sir.

**Comment by biologyscience** [comment]
> Coming March is already over sir.

Yep nevermind that, hopefully the app will be completed by the 100th release 👍

**Comment by biologyscience** [comment]
Although you can run the app by following these [instructions](https://github.com/biologyscience/overtone/blob/main/guides%2FInstallation.md)
